### ISSUE TITLE
在 remote 类型测试中获取包元信息的方式存在问题

### ISSUE THREAD

**Issue by cyjin-yl** [255doesnotexist/lintestor#17]
```shell
[2024-09-22T20:50:07Z DEBUG lintestor::test_runner::remote] CommandOutput { command: "source ./debian/apache/metadata.sh && echo $PACKAGE_VERSION && echo $PACKAGE_PRETTY_NAME && echo $PACKAGE_TYPE && echo $PACKAGE_DESCRIPTION", exit_status: 1, output: "" }
thread 'main' panicked at src/test_runner/remote.rs:227:54:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:148:5
   3: core::option::unwrap_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:2020:5
   4: core::option::Option<T>::unwrap
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:970:21
   5: <lintestor::test_runner::remote::RemoteTestRunner as lintestor::test_runner::TestRunner>::run_test
             at ./src/test_runner/remote.rs:227:34
   6: lintestor::run_tests
             at ./src/main.rs:214:19
   7: lintestor::main
             at ./src/main.rs:50:9
   8: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cyjin-yl** [comment]
观测易发现调用的元数据脚本目录不正确。

**Comment by cyjin-yl** [comment]
已修复，通过 https://github.com/255doesnotexist/lintestor/commit/cd29cd491a64578dfd03dd9942d62c457085f47c https://github.com/255doesnotexist/lintestor/commit/451e0a789057f6343b3af0c7218e8b1d3a2ab4aa 。
